### ISSUE TITLE
Not able to access 'handlebars' from jsreport-handlebars

### ISSUE THREAD

**Issue by rchancey** [jsreport/jsreport-handlebars#5] opened 2018-08-10 20:54 UTC
I am trying to add the handlebars-helpers. I am using the jsreport-handlebars package.

const handlebars = require('jsreport-handlebars')
jsreport.use(handlebars())

when I try to load the handlebars-helpers:
const helpers = require('handlebars-helpers');
and then pass it the handlebars as suggested:
jsreport.use(helpers({
    handlebars: handlebars
  }))

I get a type error on hbs.. 

module initialization error: TypeError
at /var/task/node_modules/handlebars-helpers/index.js:36:11
at forIn (/var/task/node_modules/for-in/index.js:12:12)
at helpers (/var/task/node_modules/handlebars-helpers/index.js:35:5)
at Object.<anonymous> (/var/task/lib/reporting.js:52:14)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/index.js:3:18)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

how do I add the helpers to the handlebar when it is wrapped by jsreport-handlebars?

Any example here?

**Comment by pofider** [comment] 2018-08-12 13:36
This seems like duplicate of the conversation on forum
https://forum.jsreport.net/topic/650/how-to-access-handlebars-engine-from-jsreport-handlebars/13

**Comment by bjrmatos** [comment] 2018-08-14 14:28
the answer and details were provided [here](https://forum.jsreport.net/topic/650/how-to-access-handlebars-engine-from-jsreport-handlebars/15) (with an example showing how it works)

**Closed as completed by bjrmatos** 2018-08-14 14:28 UTC
